# Ansible playbook AWS - install tshark
---
- hosts: users
  become: yes
  tasks:

  - name: Let non root to capture traffic
    ansible.builtin.debconf:
      name: wireshark-common
      question: wireshark-common/install-setuid
      value: 'true'
      vtype: boolean  

  - name: Install CLI wireshark (TShark)
    apt:
      name: tshark
      state: present
      update_cache: yes
  
  - name: Add user to wireshark group
    user:
      name: "{{ ansible_user }}"
      groups: wireshark, docker
      append: yes 
  
  - name: Restart the virtual machine for changes to take effect
    reboot:
      test_command: "groups"